name: Scheduled Node Command

on:
  schedule:
    - cron: '0 0 * * *' # This schedule runs at midnight every day (Enter your desired schedule in the cron string)

jobs:
  run-node-command:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm ci

      - name: Run Node command
        run: npx shroom dump --url https://www.habbo.com/gamedata/external_variables/326b0a1abf9e2571d541ac05e6eb3173b83bddea --location ./public/resources