name: Scheduled Node Command

on:
  schedule:
    - cron: "0 14 * * *" # This schedule runs at 11 AM ET (1 PM UTC) every day
  workflow_dispatch:

jobs:
  run-node-command:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }} # Use the new secret here instead of GITHUB_TOKEN

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19 # Specify the Node.js version you want to use

      - name: Install dependencies
        run: |
          npm ci
          ls
          cd ./icon_loader/ && npm ci

      - name: Get latest external variables ID
        id: get-external-id
        run: |
          echo "🔍 Getting latest external variables ID..."
          
          # Use curl to follow redirects and extract the final ID
          # The /0 endpoint redirects to the current version via 307 redirects
          REDIRECT_URL=$(curl -s -I -L "https://www.habbo.com/gamedata/external_variables/0" | grep -i "^location:" | tail -1 | sed 's/location: //i' | tr -d '\r')
          
          if [ -n "$REDIRECT_URL" ]; then
            # Extract ID from the redirect URL
            EXTERNAL_ID=$(echo "$REDIRECT_URL" | sed 's/.*external_variables\///' | tr -d '\r\n')
            echo "✅ Found External Variables ID via redirect: $EXTERNAL_ID"
            
            # Verify the ID works by testing it
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://www.habbo.com/gamedata/external_variables/$EXTERNAL_ID")
            
            if [ "$HTTP_STATUS" = "200" ]; then
              echo "✅ Verified ID $EXTERNAL_ID is working (HTTP $HTTP_STATUS)"
              echo "external-id=$EXTERNAL_ID" >> $GITHUB_OUTPUT
            else
              echo "❌ ID $EXTERNAL_ID returned HTTP $HTTP_STATUS"
              exit 1
            fi
          else
            echo "❌ Could not find redirect URL"
            exit 1
          fi

      - name: Run Node command with dynamic ID
        run: |
          EXTERNAL_ID="${{ steps.get-external-id.outputs.external-id }}"
          echo "Using External Variables ID: $EXTERNAL_ID"
          npx shroom dump --url "https://habbo.com/gamedata/external_variables/$EXTERNAL_ID" --location ./
          cd ./icon_loader/ && npx hdl -c ficons

      - name: Download Pet Assets
        run: |
          EXTERNAL_ID="${{ steps.get-external-id.outputs.external-id }}"
          echo "Downloading pet assets using External Variables ID: $EXTERNAL_ID"
          node download-pets.js "https://habbo.com/gamedata/external_variables/$EXTERNAL_ID"

      - name: Compile Sprites
        working-directory: ./atlas_loader/
        run: |
          npm ci
          npm run start

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add .
          git diff-index --quiet HEAD || (git commit -m "GitHub Actions: Update downloaded files" && git push --force)
